"""Lista de clanes disponibles"""

CLANES = [
    "Ninguno",
    "Brujah",
    "Brujah antitribu",
    "Gangrel",
    "Gangrel antitribu",
    "Malkavian",
    "Malkavian antitribu",
    "Nosferatu",
    "Nosferatu antitribu",
    "Toreador",
    "Toreador antitribu",
    "Tremere",
    "Tremere antitribu",
    "Ventrue",
    "Ventrue antitribu",
    "Assamita",
    "Assamita antitribu",
    "Banu Haquim",
    "Daughters of Cacophony",
    "Followers of Set",
    "Giovanni",
    "Guruhi",
    "Lasombra",
    "Ravnos",
    "Tzimisce",
    "Tzimisce antitribu",
    "Caitiff",
    # Clanes adicionales con icono disponible
    "Abomination",
    "Ahrimane",
    "Akunanse",
    "Baali",
    "Blood Brother",
    "Gargoyle",
    "Harbinger of Skulls",
    "Hecata",
    "Ishtarri",
    "Kiasyd",
    "Ministry",
    "Nagaraja",
    "Osebo",
    "Pander",
    "Salubri",
    "Salubri antitribu",
    "Samedi",
    "True Brujah",
]

# Mapeo de nombres de clanes a archivos SVG (nombres relativos en resources/clans)
CLAN_SVG_MAP = {
    # Camarilla / Sabbat clásicos
    "Brujah": "brujah.svg",
    "Brujah antitribu": "brujahantitribu.svg",
    "Gangrel": "gangrel.svg",
    "Gangrel antitribu": "gangrelantitribu.svg",
    "Malkavian": "malkavian.svg",
    "Malkavian antitribu": "malkavianantitribu.svg",
    "Nosferatu": "nosferatu.svg",
    "Nosferatu antitribu": "nosferatuantitribu.svg",
    "Toreador": "toreador.svg",
    "Toreador antitribu": "toreadorantitribu.svg",
    "Tremere": "tremere.svg",
    "Tremere antitribu": "tremereantitribu.svg",
    "Ventrue": "ventrue.svg",
    "Ventrue antitribu": "ventrueantitribu.svg",

    # Assamitas / Banu Haquim
    "Assamita": "banuhaquim.svg",           # Alias histórico
    "Assamita antitribu": "banuhaquim.svg",  # Sin icono propio, reutiliza el mismo
    "Banu Haquim": "banu_haqim.svg",

    # Otros clanes independientes y menores
    "Daughters of Cacophony": "daughters_of_cacophony.svg",
    "Followers of Set": "ministry.svg",  # Usa el símbolo moderno del Ministerio
    "Ministry": "ministry.svg",
    "Giovanni": "giovanni.svg",
    "Guruhi": "guruhi.svg",
    "Lasombra": "lasombra.svg",
    "Ravnos": "ravnos.svg",
    "Tzimisce": "tzimisce.svg",
    "Tzimisce antitribu": "tzimisce.svg",
    "Caitiff": "caitiff.svg",

    # Clanes adicionales con símbolo específico
    "Abomination": "abomination.svg",
    "Ahrimane": "ahrimane.svg",
    "Akunanse": "akunanse.svg",
    "Baali": "baali.svg",
    "Blood Brother": "bloodbrother.svg",
    "Gargoyle": "gargoyle.svg",
    "Harbinger of Skulls": "harbingerofskulls.svg",
    "Hecata": "hecata.svg",
    "Ishtarri": "ishtarri.svg",
    "Kiasyd": "kiasyd.svg",
    "Nagaraja": "nagaraja.svg",
    "Osebo": "osebo.svg",
    "Pander": "pander.svg",
    "Salubri": "salubri.svg",
    "Salubri antitribu": "salubriantitribu.svg",
    "Samedi": "samedi.svg",
    "True Brujah": "truebrujah.svg",
}
