"""Lista de disciplinas disponibles"""

DISCIPLINAS = [
    "Abombwe",
    "Abombwe Superior",
    "Animalism",
    "Animalism Superior",
    "Auspex",
    "Auspex Superior",
    "Blood Sorcery",
    "Blood Sorcery Superior",
    "Celerity",
    "Celerity Superior",
    "Chimerstry",
    "Chimerstry Superior",
    "Daimoinon",
    "Daimoinon Superior",
    "Dementation",
    "Dementation Superior",
    "Dominate",
    "Dominate Superior",
    "Fortitude",
    "Fortitude Superior",
    "Melpominee",
    "Melpominee Superior",
    "Mytherceria",
    "Mytherceria Superior",
    "Necromancy",
    "Necromancy Superior",
    "Obeah",
    "Obeah Superior",
    "Obfuscate",
    "Obfuscate Superior",
    "Oblivion",
    "Oblivion Superior",
    "Obtenebration",
    "Obtenebration Superior",
    "Potence",
    "Potence Superior",
    "Presence",
    "Presence Superior",
    "Protean",
    "Protean Superior",
    "Quietus",
    "Quietus Superior",
    "Sanguinus",
    "Sanguinus Superior",
    "Serpentis",
    "Serpentis Superior",
    "Spiritus",
    "Spiritus Superior",
    "Temporis",
    "Temporis Superior",
    "Thanatosis",
    "Thanatosis Superior",
    "Valeren",
    "Valeren Superior",
    "Vicissitude",
    "Vicissitude Superior",
    "Visceratika",
    "Visceratika Superior",
]

# Versión filtrada para usos donde sólo se permiten niveles inferiores
# (por ejemplo, cartas de librería: sin las variantes "Superior").
DISCIPLINAS_INFERIORES = [d for d in DISCIPLINAS if not d.endswith(" Superior")]
